name: Deploy HTML files to Beget

on:
  push:
    branches: [main, master]
    paths:
      - "*.html"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Setup SSH known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.BEGET_SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy HTML files
        run: |
          # Загружаем все HTML файлы из корня репозитория
          sshpass -p "${{ secrets.BEGET_SSH_PASSWORD }}" scp -o StrictHostKeyChecking=no *.html ${{ secrets.BEGET_SSH_LOGIN }}@${{ secrets.BEGET_SSH_HOST }}:~/
